### ISSUE TITLE
Problème  carte ign hors ligne

### ISSUE THREAD

**Issue by benoitsauvard** [OsmAnd-Rendering/Online-Maps#1]
Bonjour,
Top ce ptit github pour osmand, et en plus en français.
Itineraire et profil carte vectorielle pour la moto offroad niquel.

Juste un ptit soucis, je n'arrive pas à telecharger plus de 4-5Mo de carte IGN pour du hors ligne.
Je suis le seul?
![Screenshot_20220930-082459_OsmAnd+](https://user-images.githubusercontent.com/94927596/193205029-503022e6-6c29-47f5-88a7-72a652a3bd7a.jpg)
![Screenshot_20220930-082603_OsmAnd+](https://user-images.githubusercontent.com/94927596/193205032-622d19b4-e4c3-4a19-a8e5-58326d9eff73.jpg)

**Comment by bobeeeze** [comment]
Moi je n'ai pas de problème, je viens de faire un test et j'ai téléchargé un morceau d'environs 300Mo
