### ISSUE TITLE
Añadir mapas de IGN Argentina

### ISSUE THREAD

**Issue by franco999** [OsmAnd-Rendering/Online-Maps#3]
Será posible añadir en el listado los mapas de @ign-argentina y así poder hacer más fácil su importación a OsmAnd?

Algunas direcciones TMS a usar en OsmAnd se pueden encontrar en https://www.ign.gob.ar/NuestrasActividades/InformacionGeoespacial/ServiciosOGC y primero se deberían convertir a un formato compatible como `.sqlitedb`

Por lo que pude encontrar, la licencia de Argenmap sería GPL-3.0

**Comment by bobeeeze** [comment]
Ya están disponible los sqlitedb para visualizar los mapas del @ign-argentina
